version: '3.8'

services:
  app:
    build: .
    ports:
      - "5021:5021"
    volumes:
      - ./trips:/usr/src/app/trips
    restart: unless-stopped
    # Add network_mode: "host" for Windows to make host.docker.internal work
    # This is needed for Windows Docker Desktop
    network_mode: "host"
